IF (OPENJPEG_INCLUDE_DIR AND OPENJPEG_LIBRARY)
  # Already in cache, be silent
  SET(OpenJPEG_FIND_QUIETLY TRUE)
ENDIF (OPENJPEG_INCLUDE_DIR AND OPENJPEG_LIBRARY)


FIND_PATH(OPENJPEG_INCLUDE_DIR NAMES openjpeg.h PATHS
  /usr/local/include
  /usr/include
)

FIND_LIBRARY(OPENJPEG_LIBRARY NAMES openjpeg PATHS ${OPENJPEG_INCLUDE_DIR}/../lib)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenJPEG DEFAULT_MSG OPENJPEG_LIBRARY OPENJPEG_INCLUDE_DIR)
MARK_AS_ADVANCED(OPENJPEG_INCLUDE_DIR OPENJPEG_LIBRARY)
